services:
  mysql:
    image: mysql:8.0
    container_name: cache-n-carry-mysql-dev
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: